# Generated by Django 5.1.2 on 2024-10-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Flan',
        ),
    ]
