# Generated by Django 5.1.2 on 2024-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_model_flan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
