# Generated by Django 5.1.2 on 2024-10-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_conctactform_alter_flan_flan_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConctactForm',
            new_name='ContactForm',
        ),
    ]
